from cppmakelib.unit.binary        import Binary
from cppmakelib.utility.filesystem import path

class Preparsed(Binary):
    def __new__ (cls,  file: path) -> Preparsed: ...
    def __init__(self, file: path) -> None     : ...