from cppmakelib.unit.package       import Package
from cppmakelib.utility.decorator  import member, unique
from cppmakelib.utility.filesystem import path

class Binary:
    def           __new__  (cls,  file       : path) -> Binary: ...
    def           __init__ (self, file       : path) -> None  : ...
    def             install(self, install_dir: path) -> Binary: ...
    async def async_install(self, install_dir: path) -> Binary: ...
    def             sign   (self)                    -> Binary: ...
    async def async_sign   (self)                    -> Binary: ...
    def             strip  (self)                    -> Binary: ...
    async def async_strip  (self)                    -> Binary: ...
    file          : path
    belong_package: Package
    link_flags    : list[str]



@member(Binary)
@unique
def __init__(self: Binary, file: path) -> None:
    self.file           = file
    self.belong_package = Package._which_contains(self.file)
    self.link_flags     = self.belong_package.link_flags
