from cppmakelib.unit.executable    import Executable
from cppmakelib.unit.object        import Object
from cppmakelib.utility.filesystem import path

class Dynamic:
    def           __new__ (self, file: path) -> Dynamic   : ...
    def           __init__(self, file: path) -> None      : ...
    def             link  (self)             -> Executable: ...
    async def async_link  (self)             -> Executable: ...
    file           : path
    executable_file: path
    require_objects: list[Object]
