from cppmakelib.executor.run        import async_run
from cppmakelib.executor.scheduler  import scheduler
from cppmakelib.system.all          import system
from cppmakelib.unit.binary         import Binary
from cppmakelib.unit.object         import Object
from cppmakelib.utility.decorator   import once, syncable, trace, unique
from cppmakelib.utility.filesystem  import path

class Executable(Binary):
    def           __new__  (self, file: path) -> Executable: ...
    def           __init__ (self, file: path) -> None      : ...
    def             execute(self)             -> None      : ...
    async def async_execute(self)             -> None      : ...
    def             test   (self)             -> None      : ...
    async def async_test   (self)             -> None      : ...
    file: path


