from cppmakelib.unit.binary        import Binary
from cppmakelib.unit.dynamic       import Dynamic
from cppmakelib.unit.executable    import Executable
from cppmakelib.unit.object        import Object
from cppmakelib.utility.filesystem import path

class Static(Binary):
    def          __new__   (self, file: path) -> Static      : ...
    def          __init__  (self, file: path) -> None        : ...
    def             share  (self)             -> Dynamic     : ...
    async def async_share  (self)             -> Dynamic     : ...
    def             link   (self)             -> Executable  : ...
    async def async_link   (self)             -> Executable  : ...
    def             extract(self)             -> list[Object]: ...
    async def async_extract(self)             -> list[Object]: ...
    file           : path
    dynamic_file   : path
    executable_file: path
    require_objects: list[Object]
