class MakeProgressLogger:
    def info   (self, message: str) -> None: ...
    def warning(self, message: str) -> None: ...
    def error  (self, message: str) -> None: ...

make_progress_logger: MakeProgressLogger