import asyncio

def sync_wait     (task ): ...
def start_detached(task ): ...
def ensure_started(task ): ...
def when_all      (tasks): ...
def when_any      (tasks): ...



def sync_wait(task):
    return asyncio.run(task)

async def when_all(tasks):
    return await asyncio.gather(*tasks)