from cppmakelib.unit.binary        import Binary
from cppmakelib.utility.filesystem import path

class Precompiled(Binary):
    def __new__ (cls,  file: path) -> Precompiled: ...
    def __init__(self, file: path) -> None       : ...