from cppmakelib.utility.filesystem import path
import typing
if typing.TYPE_CHECKING:
    from cppmakelib.unit.code    import Code
    from cppmakelib.unit.module  import Module
    from cppmakelib.unit.package import Package
    from cppmakelib.unit.object  import Object
    from cppmakelib.unit.source  import Source

class UnitStatusLogger:
    def __init__               (self)                                       -> None      : ...
    def __del__                (self)                                       -> None      : ...
    def get_package_built      (self, package: Package)                     -> bool      : ...
    def set_package_built      (self, package: Package, result: bool)       -> None      : ...
    def get_code_preprocessed  (self, code   : Code)                        -> bool      : ...
    def set_code_preprocessed  (self, code   : Code,    result: bool)       -> None      : ...
    def get_module_imports     (self, module : Module)                      -> list[path]: ...
    def set_module_imports     (self, module : Module,  result: list[path]) -> None      : ...
    def get_module_name        (self, file   : path)                        -> str       : ...
    def set_module_name        (self, file   : path,    result: str)        -> None      : ...
    def get_module_file        (self, name   : str)                         -> path      : ...
    def set_module_file        (self, name   : str,     result: path)       -> None      : ...
    def get_module_precompiled (self, module : Module)                      -> bool      : ...
    def set_module_precompiled (self, module : Module,  result: bool)       -> None      : ...
    def get_source_imports     (self, source : Source)                      -> list[path]: ...
    def set_source_imports     (self, source : Source,  result: list[path]) -> None      : ...
    def get_source_compiled    (self, source : Source)                      -> bool      : ...
    def set_source_compiled    (self, source : Source,  result: bool)       -> None      : ...
    def get_object_requires    (self, object : Object)                      -> list[path]: ...
    def set_object_requires    (self, object : Object,  result: list[path]) -> None      : ...
    

unit_status_logger: UnitStatusLogger
